# Generated by Django 2.0 on 2018-01-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekurser', 'initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupazajeciowa',
            options={'managed': False, 'ordering': ['liczbauczestnikow']},
        ),
    ]
