# Generated by Django 2.0 on 2018-01-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekurser', '0001_auto_20180121_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dzientygodnia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grupazajeciowa',
            options={'ordering': ['liczbauczestnikow']},
        ),
        migrations.AlterModelOptions(
            name='kurs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kurskurs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kwalifikacje',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nauczycielakademicki',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opieka',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opinia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prowadzenie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rodzajgrupy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statuswniosku',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='termin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uczestnictwo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wniosekouruchomieniegrupyzajeciowej',
            options={},
        ),
    ]
