# Generated by Django 2.0 on 2018-01-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DzienTygodnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'dzientygodnia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupaZajeciowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czyuruchomiona', models.BooleanField()),
                ('liczbamiejsc', models.IntegerField()),
                ('liczbauczestnikow', models.IntegerField()),
            ],
            options={
                'db_table': 'grupazajeciowa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartoscgodzinowa', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('nazwakursu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KursKurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'kurs_kurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kwalifikacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nauczycielakademicki_kurs2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NauczycielAkademicki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('liczbagodzin', models.IntegerField()),
                ('pensum', models.IntegerField()),
                ('jestpelnomocnikiem', models.BooleanField()),
            ],
            options={
                'db_table': 'nauczycielakademicki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opieka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nauczycielakademicki_kurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'opinia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prowadzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'grupazajeciowa_nauczycielakademicki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RodzajGrupy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'rodzajgrupy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusWniosku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'statuswniosku',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('nrindeksu', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godzina', models.CharField(blank=True, max_length=10, null=True)),
                ('sala', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'termin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uczestnictwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'student_grupazajeciowa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WniosekOUruchomienieGrupyZajeciowej',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zgodapelnomocnika', models.NullBooleanField()),
                ('nrwniosku', models.IntegerField()),
            ],
            options={
                'db_table': 'wniosekouruchomieniegrupyzajeciowej',
                'managed': False,
            },
        ),
    ]
